### ISSUE TITLE
Issue on linux/clang-3.8.1 and clang-3.9

### ISSUE THREAD

**Issue by acgetchell** [docopt/docopt.cpp#50]
Here's the error I get building docopt.cpp with clang-3.8.1 or 3.9 on ubuntu-14.04:

```
FAILED: /usr/bin/clang++-3.9   -DCGAL_EIGEN3_ENABLED -DCGAL_LINKED_WITH_TBB -DCGAL_USE_GMP -DCGAL_USE_MPFR -DNOMINMAX -O3 -DNDEBUG -I../src -I../. -I../../../include -isystem /usr/include/x86_64-linux-gnu -I. -I/usr/local/include -isystem /usr/include/eigen3    -std=gnu++14 -MMD -MT CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o -MF CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o.d -o CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o -c ../src/docopt/docopt.cpp
In file included from ../src/docopt/docopt.cpp:9:
In file included from ../src/docopt/docopt.h:12:
In file included from ../src/docopt/docopt_value.h:12:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
```

You can see full logs from my Travis-CI builds here:

Clang 3.8.1
https://travis-ci.org/acgetchell/CDT-plusplus/jobs/146769356

Clang 3.9
https://travis-ci.org/acgetchell/CDT-plusplus/jobs/146771517

It works fine with gcc or AppleClang.

**Comment by jaredgrubb** [comment]
These are errors ocurring in the standard library .. seems like something is messed up in your environment?

**Comment by acgetchell** [comment]
It's the Travis-CI trusty environment (Ubuntu Trusty-Tahr 14.04.3 LTS) with Clang 3.9. I'll look to see if this works with the default clang-3.5.

**Comment by jaredgrubb** [comment]
@acgetchell Did you get a chance to try it?

**Comment by acgetchell** [comment]
No, I thought it was a boost error but still not working. Unfortunately, I can't go back to Clang 3.5 anymore as I'm using some feature it doesn't support (probably having to do with function_ref.h or boost::optional with reference bindings).

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/200582999

~~~
[3/22] Building CXX object CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o
FAILED: /usr/bin/clang++-3.9   -DCGAL_EIGEN3_ENABLED -DCGAL_LINKED_WITH_TBB -DCGAL_USE_GMP -DCGAL_USE_MPFR -DNOMINMAX -O3 -DNDEBUG -I../src -I../. -I../../../include -isystem /usr/include/x86_64-linux-gnu -I. -I/usr/local/include -isystem /usr/include/eigen3    -Wall -Wextra -std=gnu++14 -MMD -MT CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o -MF CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o.d -o CMakeFiles/cdt.dir/src/docopt/docopt.cpp.o -c ../src/docopt/docopt.cpp
In file included from ../src/docopt/docopt.cpp:9:
In file included from ../src/docopt/docopt.h:12:
In file included from ../src/docopt/docopt_value.h:12:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
~~~

**Comment by jaredgrubb** [comment]
It's a bug in the standard library you're using:
http://stackoverflow.com/questions/17775390/clang-3-3-in-c1y-mode-cannot-parse-cstdio-header
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51785

Seems like you're using clang but against libstd++ from GCC4.8. Can you not use libc++?

**Comment by acgetchell** [comment]
Ah, thanks for the heads up. Looks like I'll have to fiddle with Travis some more.
