### ISSUE TITLE
Won't compile with g++ 4.9 on Linux

### ISSUE THREAD

**Issue by ntc490** [docopt/docopt.cpp#2]
Unable to build using g++ 4.9 on Ubuntu 14.04.  LMK if I can help sort things out.

<session>
ntc490@prompus:~/src/docopt.cpp$ g++ -std=c++0x docopt.cpp run_testcase.cpp -o run_testcase
docopt.cpp: In instantiation of ‘struct longOptions(I, I) [with I = __gnu_cxx::__normal_iterator<const docopt::Option**, std::vector<const docopt::Option*> >]::__lambda9’:
docopt.cpp:574:70:   required from ‘std::vectorstd::basic_string<char > longOptions(I, I) [with I = __gnu_cxx::__normal_iterator<const docopt::Option**, std::vector<const docopt::Option*> >]’
docopt.cpp:611:81:   required from here
docopt.cpp:574:39: error: ‘const’ qualifiers cannot be applied to ‘const docopt::Option_&’
          [](decltype%28*iter%29 const& opt) { return opt->longOption(); });
                                       ^
docopt.cpp:574:36: error: ‘const’ qualifiers cannot be applied to ‘const docopt::Option_&’
          [](decltype%28*iter%29 const& opt) { return opt->longOption(); });
                                    ^
docopt.cpp:574: confused by earlier errors, bailing out
Preprocessed source stored into /tmp/cctuWJ9W.out file, please attach this to your bugreport.
In file included from docopt.h:12:0,
                 from run_testcase.cpp:9:
docopt_value.h:222:7: warning: inline function ‘void docopt::hash_combine(std::size_t&, const T&) [with T = std::basic_string<char>; std::size_t = unsigned int]’ used but never defined [enabled by default]
  void hash_combine(std::size_t& seed, const T& v);
       ^
</session>
